import Head from "next/head"
import { useEffect, useState } from "react";
import { Button, Card, Layout, message } from "antd";
import { getAuthToken } from "../utils/authUtils";
import { logout, verifyUser } from "../services/auth";
import Image from "next/image";
import { useRouter } from "next/router";

const { Content } = Layout;

const Dashboard = () => {
    const [userDetails, setUserDetails] = useState(null);
    const router = useRouter();

    useEffect(() => {
        const user = getAuthToken();
        if (!user) {
            message.error("User acess denied!");
            logout();
        } else {
            verifyUser(user).then((response) => {
                setUserDetails(response.data)
            }).catch(() => {
                message.error("User Acess expired!")
                logout();
            })
        }
    }, [])

    const handleLogout = () => {
        logout();
        router.push("/");
    }

    return (
        <Layout>
            <Head>
                <title>Sunrise MGMT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Content className="p-6">
                <div className="flex flex-col w-full md:max-w-md md:mx-auto">
                    <div className='flex justify-center mb-6'>
                        <Image width={200} height={200} src="/logo.png" alt="logo" />
                    </div>
                    {
                        userDetails ?
                            <Card className="mb-10">
                                <div className="flex flex-col items-center">
                                    <h1 className="font-normal text-center">{userDetails?.Name}</h1>
                                    <h3 className="font-normal text-center my-4">{userDetails?.its}</h3>
                                    <h3 className="font-normal text-center">{"+91" + userDetails.Whatsapp}</h3>
                                </div>
                            </Card> : null
                    }
                    <Card
                        className="mb-4 border-1 border-solid border-[#501800] cursor-pointer"
                        onClick={() => router.push("/profile")}
                    >
                        <p className="text-center text-2xl mb-0 text-[#501800]">Profile</p>
                    </Card>
                    {/* <Card className="mb-4 border-1 border-solid border-[#501800]">
                        <p className="text-center text-2xl mb-0 text-[#501800]">Duties</p>
                    </Card> */}
                    <Card
                        className="mb-4 border-1 border-solid border-[#501800] cursor-pointer"
                        onClick={() => router.push("/accounts")}
                    >
                        <p className="text-center text-2xl mb-0 text-[#501800]">Accounts</p>
                    </Card>
                    <Button onClick={handleLogout} size="large" type="primary" className="bg-red-500">Logout</Button>
                </div>
            </Content>

        </Layout>
    )
}

export default Dashboard