import { Button, Card, Form, InputNumber, message } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import { login, logout, verifyUser } from '../services/auth'
import { getAuthToken, saveAuthToken } from '../utils/authUtils'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { FullPageLoader } from '../components'

export default function Login() {

  const router = useRouter();

  const [showLoader, setShowLoader] = useState(false);

  const redirectBasedOnUser = () => {
    router.push("/dashboard");
  };

  const handleLogin = (values) => {
    setShowLoader(true)
    login(values)
      .then(response => {
        saveAuthToken(response.data)
        return response.data
      }).then(() => {
        redirectBasedOnUser()
      })
      .catch(error => message.error(error))
      .finally(() => {
        setShowLoader(false)
      })
  }

  useEffect(() => {
    const user = getAuthToken();
    if (!!user) {
      verifyUser(user).then(() => {
        redirectBasedOnUser();
      }).catch(() => {
        logout()
      })
    }
  }, [])


  return (
    <div className='flex items-center justify-center p-6 min-h-screen'>
      <Head>
        <title>Sunrise MGMT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {
        showLoader ? <FullPageLoader /> : null
      }

      <Card className='w-full md:max-w-sm'>
        <div className='flex justify-center '>
          <Image width={150} height={150} src="/logo.png" alt="logo" />
        </div>
        <h1 className='text-2xl text-center mb-8'>Login</h1>
        <Form
          name="login"
          onFinish={handleLogin}
          requiredMark={false}
          layout="vertical"
          size='large'
        >
          <Form.Item
            label=""
            name="its"
            rules={[
              {
                required: true,
                message: 'Please input your its!',
              },
            ]}
          >
            <InputNumber placeholder='Enter ITS' className='w-full' />
          </Form.Item>

          <Form.Item className='text-center'>
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>
      </Card>

    </div>
  )
}
