import Head from "next/head"
import { useEffect, useState } from "react";
import { Button, Card, Layout, message } from "antd";
import { getAuthToken } from "../utils/authUtils";
import { logout, verifyUser } from "../services/auth";
import Image from "next/image";
import { useRouter } from "next/router";
import {
    ArrowLeftOutlined
} from '@ant-design/icons';
const { Content } = Layout;

const Profile = () => {
    const [userDetails, setUserDetails] = useState(null);
    const router = useRouter();

    useEffect(() => {
        const user = getAuthToken();
        if (!user) {
            message.error("User acess denied!");
            logout();
            router.push("/");
        } else {
            verifyUser(user).then((response) => {
                setUserDetails(response.data)
            }).catch(() => {
                message.error("User Acess expired!")
                logout();
                router.push("/");
            })
        }
    }, [])

    const goBack = () => {
        router.push("/dashboard");
    }

    return (
        <Layout>
            <Head>
                <title>Sunrise MGMT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Content className="p-6">
                <Button onClick={goBack} type="link" className="mb-4 text-left text-[#555555]"><ArrowLeftOutlined /> Go Back</Button>
                <div className="flex flex-col w-full md:max-w-md md:mx-auto">
                    <div className='flex justify-center mb-6'>
                        <Image width={200} height={200} src="/logo.png" alt="logo" />
                    </div>
                    {
                        userDetails ?
                            <Card className="mb-10">
                                <div className="flex flex-col items-center">
                                    <h1 className="font-normal text-center">{userDetails?.Name}</h1>
                                    <h3 className="font-normal text-center my-4">{userDetails?.its}</h3>
                                    <h3 className="font-normal text-center">{"+91" + userDetails.Whatsapp}</h3>
                                </div>
                            </Card> : null
                    }

                </div>
            </Content>

        </Layout>
    )
}

export default Profile